### ISSUE TITLE
Ruby exception occurred

### ISSUE THREAD

**Issue by mib4fun** [bitsofinfo/logstash-modsecurity#36]
Hello,

From times to times, i got a ruby exception 
```
Ruby exception occurred: undefined method `/' for nil:NilClass {:level=>:error}
Ruby exception occurred: undefined method `/' for nil:NilClass {:level=>:error}
Ruby exception occurred: no implicit conversion from nil to integer {:level=>:error}
Ruby exception occurred: undefined method `/' for nil:NilClass {:level=>:error}
Ruby exception occurred: undefined method `/' for nil:NilClass {:level=>:error}
Ruby exception occurred: no implicit conversion from nil to integer {:level=>:error}
Ruby exception occurred: undefined method `/' for nil:NilClass {:level=>:error}
....
```

I'm using logstash 2.4 with master branch

**Comment by mib4fun** [comment]
I got that somes times
```
{
    "@timestamp" => "2016-09-09T14:38:22.019Z",
       "message" => "ed=10301, p1=177, p2=10045, p3=2, p4=21, p5=55, sr=12, sw=1, l=0, gc=0\nResponse-Body-Transformed: Dechunked\nProducer: ModSecurity for nginx (STABLE)/2.8.0 (http://www.modsecurity.org/); OWAS
P_CRS/2.2.9.\nServer: ModSecurity Standalone\nEngine-Mode: \"ENABLED\"\n--33b79b01-Z--",
      "@version" => "1",
          "tags" => [
        [0] "multiline",
        [1] "_grokparsefailure",
        [2] "_rubyexception"
    ],
          "path" => "/var/log/nginx/modsecurity/20160909/20160909-1438/20160909-143817-Ac8cfcAcbcAtAcAcTcAcAcAc",
          "host" => "ANY",
          "type" => "mod_security"
}
```

**Comment by bitsofinfo** [comment]
That is a error parsing something in your inbound event content. If you track it down, feel free to submit a PR

**Comment by mib4fun** [comment]
It seems there is an issue with the logstash multiline codec when parsing  large set of data.
I use now filebeat like this

```
      paths:
        - /var/log/nginx/modsecurity/*/*/*
      input_type: log
      force_close_files: true
      exclude_lines: ['--[a-fA-F0-9]{8}-Z--$']
      encoding: us-ascii
      document_type: mod_security
      scan_frequency: 0s
      multiline:
        pattern: '--[a-fA-F0-9]{8}-Z--$'
        negate: true
        match: after
```

The logstash filter is all good now.
